### PR TITLE
simple Matrix Graph

### PR DESCRIPTION
**Pull request by JunJul**
We can create either a directed graph or an undirected graph according to the flag if the flag is false which means undirected; otherwise, it is directed insert vertex and return its index which will be used for insertEdge for example if we have A and B two vertices in the array, which are index 0, 1 so insert the edge in edges[0][1] and edges[1][0] if it is an undirected graph if it is directed, only need to do edges[0][1]

### CODE REVIEW

**Comment by JunJul** [comment]
Please. Add me a hacktoberfest-accepted label, thank you.

**Comment by ritviksharma3** [comment]
Happy Contributing!

**Comment by JunJul** [comment]
@ritviksharma3 Why is your repos excluded from the Hacktoberfest?

**Comment by JunJul** [comment]
Screenshot (22)

**Comment by JunJul** [comment]
@ritviksharma3

**Comment by JunJul** [comment]
@ritviksharma3 
Screenshot (22)

**Comment by JunJul** [comment]
@ritviksharma3 
Screenshot (22)

**Pull request merged**
